---
network:
  topology: ring  # line, lattice, ring, full, smallworld
  self_delay: 0.25  # inter-node delay
  node_distance: 1  # intra-node distance
  signal_velocity: 2  # intra-node velocity
  N: 50  # Number of network nodes
  p: 0.2  # For ring network, proportion of neighbours


delay: 
  type: constant  # constant, distribution, geometric
  distribution: uniform  # uniform, normal
  mean: 0  # for normal
  std: 1  # for normal
  min: 1  # for uniform
  max: 10  # for uniform


coupling:
  type: constant
  value: 1
  distribution: None

simulation:
  duration: 1000
  dt: 0.1
  n_runs: 10

model:
  name: wilson_cowan
  params:
    a: 1


